### ISSUE TITLE
[feature request] accept a function on `filter` param of `discover()` method

### ISSUE THREAD

**Issue by dayflower** [futomi/node-dns-sd#2]
I would appreciate it if this product could also accept a function on `filter` param of `discover()` method.

Like this:

```javascript
mDnsSd.discover({
  name: '_googlecast._tcp.local',
  filter: (device) => {
    return device['modelName'] && device['modelName'] === 'Google Home Mini'
        && device['familyName'] && device['familyName'] === 'Living Room'
  }
});
```

**Comment by futomi** [comment]
Thank you so much for your feedback. That's a nice idea! I'll implement the `filter` parameter to the `discover()` method soon. Give me some time.

**Comment by futomi** [comment]
I implemented the function-based filter in the `discover()` method. Try the latest version.

**Comment by dayflower** [comment]
Great!

thanks
