### ISSUE TITLE
Error on udp.addMembership Method

### ISSUE THREAD

**Issue by SlyAndrew** [futomi/node-dns-sd#4]
If an interface, due to dhcp release time, have more than a one IPv4 the addMembership method of udp fall into an error that cause an uncatchable error that restarts the node process.
I fixed the error just add a try/catch state on row 423 of dns-sd.js

**Comment by SlyAndrew** [comment]
Here an example of my Ip address when I fall on the error:
`
`
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel qlen 1000
    link/ether b8:27:eb:4b:c4:06 brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.21/24 brd 192.168.10.255 scope global dynamic eth0
       valid_lft 86365sec preferred_lft 86365sec
    inet 192.168.10.23/24 brd 192.168.10.255 scope global secondary dynamic eth0
       valid_lft 86366sec preferred_lft 86366sec
    inet6 fe80::f44c:ad8c:1f0a:bcd6/64 scope link 
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel qlen 1000
    link/ether b8:27:eb:1e:91:53 brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.10/24 brd 192.168.10.255 scope global dynamic wlan0
       valid_lft 77586sec preferred_lft 77586sec
    inet6 fe80::9976:151f:d1f6:589d/64 scope link 
       valid_lft forever preferred_lft forever
`
`

**Comment by futomi** [comment]
Thank you so much! I merged your PR and updated the [package on npm](https://www.npmjs.com/package/node-dns-sd).
